watcher.actions.email.service.account:
    work:
        profile: standard
        email_defaults:
            from: amitpatelinfo@sendgrid.com
        smtp:
            auth: true
            starttls.enable: true
            host: smtp.sendgrid.net
            port: 465
            user: amitpatelinfo
            password: "@mit@1234"

watcher.actions.slack.service:
  account:
      monitoring:
        url: https://hooks.slack.com/services/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
        message_default:
          from: Watcher
